robot_config: 5
robot_front: $(env ROBOT_FRONT)
robot_rotation_x: $(env ROBOT_ROTATION_X)
robot_rotation_y: $(env ROBOT_ROTATION_Y)
robot_left: $(env ROBOT_LEFT)
robot_right: $(env ROBOT_RIGHT)
robot_rear: $(env ROBOT_REAR)
robot_height: $(env ROBOT_HEIGHT)
robot_manual_x: $(env ROBOT_MANUAL_X)
robot_manual_y: $(env ROBOT_MANUAL_Y)
robot_teleop_x: $(env ROBOT_TELEOP_X)
robot_teleop_y: $(env ROBOT_TELEOP_Y)
robot_autonomous_x: $(env ROBOT_AUTONOMOUS_X)
robot_autonomous_y: $(env ROBOT_AUTONOMOUS_Y)
robot_throttle_x: $(env ROBOT_THROTTLE_X)
robot_throttle_y: $(env ROBOT_THROTTLE_Y)
