global_costmap:
  global_frame: map
  footprint_padding: $(env ROBOT_PADDING)
  resolution: $(env UV_MAP_RESOLUTION)
  robot_base_frame: base_link
  update_frequency: 6.0
  origin_x: -50
  origin_y: -50
  width: 100
  height: 100
  publish_frequency: 6.0
  static_map: true
  rolling_window: false
  track_unknown_space: true
  always_send_full_costmap: true
  plugins:
    - {name: static,                  type: "costmap_2d::StaticLayer"}
    - {name: global_obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: static_obstacles,           type: "costmap_2d::StaticLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
