ARG BASE_IMAGE
ARG DEV_IMAGE
FROM ${DEV_IMAGE} as dev

FROM ${BASE_IMAGE}
COPY --from=dev /opt/phoenix1/ /opt/phoenix1/
COPY --from=dev /opt/underlay_ws/ /opt/underlay_ws/

# adding entery point
COPY binder/prod/entrypoint /tmp/prod_entrypoint
ENTRYPOINT ["/tmp/prod_entrypoint"]
CMD ["/bin/sh", "-c", "trap 'exit 147' TERM; tail -f /dev/null & wait ${!}"]
