#!/bin/bash

# Install global npm packages
npm install -g $(cut -d# -f1 <binder/npm.txt)

# Install claat
# wget -P /usr/local/bin https://github.com/googlecodelabs/tools/releases/download/v2.2.0/claat-linux-amd64
# mv /usr/local/bin/claat-linux-amd64 /usr/local/bin/claat
# chmod +x /usr/local/bin/claat

eval $(/home/jovyan/.local/bin/brew shellenv)
brew install $(cut -d# -f1 <~/binder/brew.txt)
